/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package belajar.gradle

class App {
    val greeting: String
        get() {
            return "Hello world"
        }
}

fun main() {
    println(App().greeting)
    println("belajar Kotlin")
    val zaxx : Char = ('A')
    println(zaxx)
}
